spring:
  kafka:
    bootstrap-servers:
      - "10.0.0.20:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.DoubleSerializer