{
 "title": "Finance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bitcoin Course",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"finance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement==\"finance-bitcoin\")\r\n  |> yield(name: \"value bitcoin\")"
    }
   ]
  },
  {
   "title": "Bitcoin",
   "type": "candlestick",
   "gridPos": { "h": 13, "w": 8, "x": 9, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"finance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement==\"finance-bitcoin\")\r\n  |> yield(name: \"value bitcoin\")"
    }
   ]
  },
  {
   "title": "News Feed",
   "type": "news",
   "gridPos": { "h": 26, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_time AS \"time\",\n  id\nFROM weather\nWHERE\n  $__timeFilter(created_time)\nORDER BY created_time"
    }
   ]
  },
  {
   "title": "Ethereum Course",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"finance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement==\"finance-ethereum\")\r\n  |> yield(name: \"value bitcoin\")"
    }
   ]
  },
  {
   "title": "Ethereum",
   "type": "candlestick",
   "gridPos": { "h": 13, "w": 8, "x": 9, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"finance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement==\"finance-ethereum\")\r\n  |> yield(name: \"value bitcoin\")"
    }
   ]
  },
  {
   "title": "Current Value",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"finance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> yield(name: \"value bitcoin\")"
    }
   ]
  },
  {
   "title": "Average Value",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"finance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> yield(name: \"value bitcoin\")"
    }
   ]
  },
  {
   "title": "MinimumValue",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "from(bucket: \"finance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> yield(name: \"value bitcoin\")"
    }
   ]
  },
  {
   "title": "Maximum Value",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"finance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> yield(name: \"value bitcoin\")"
    }
   ]
  }
 ]
}