{
 "title": "Weather_v2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Highest Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> yield(name: \"humidity\")"
    }
   ]
  },
  {
   "title": "Temperature Histogram",
   "type": "histogram",
   "gridPos": { "h": 20, "w": 6, "x": 17, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> yield(name: \"pressure\")"
    }
   ]
  }
 ]
}